services:
  - type: web
    name: full-stack-project-remix-iamtati1
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: SESSION_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CLIENT_URL
        sync: false

  - type: static
    name: taskflow
    buildCommand: npm install --include=dev --prefix frontend && npm run build --prefix frontend
    staticPublishPath: ./frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://full-stack-project-remix-iamtati1.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
